#!/bin/sh

set -C -f -u
IFS=$'\n'

# ANSI color codes are supported.
# STDIN is disabled, so interactive scripts won't work properly

# This script is considered a configuration file and must be updated manually.

# Meanings of exit codes:
# code | meaning    | action of ranger
# -----+------------+-------------------------------------------
# 0    | success    | Display stdout as preview
# 1    | no preview | Display no preview at all
# 2    | plain text | Display the plain content of the file

# Script arguments
FILE_PATH="${1}"         # Full path of the highlighted file
HEIGHT="${2}"

FILE_EXTENSION="${FILE_PATH##*.}"
FILE_EXTENSION_LOWER=$(echo ${FILE_EXTENSION} | tr '[:upper:]' '[:lower:]')

# Settings
HIGHLIGHT_SIZE_MAX=262143  # 256KiB
HIGHLIGHT_TABWIDTH=8
HIGHLIGHT_STYLE='pablo'

handle_extension() {
    case "${FILE_EXTENSION_LOWER}" in
        a|ace|alz|arc|arj|bz|bz2|cab|cpio|deb|gz|jar|lha|lz|lzh|lzma|lzo|\
        rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip)
		atool --list "${FILE_PATH}";;
        rar) unrar lt -p- -- "${FILE_PATH}" exit 1;;
        7z) 7z l -p -- "${FILE_PATH}" exit 1;;
        pdf) pdftotext -l 10 -nopgbrk -q -- "${FILE_PATH}" -
             mutool draw -F txt -i -- "${FILE_PATH}" 1-10
             exiftool "${FILE_PATH}" exit 1;;
	md) glow -s dark "${FILE_PATH}" exit 1;;
        torrent) transmission-show -- "${FILE_PATH}" exit 1;;
        odt|ods|odp|sxw) odt2txt "${FILE_PATH}" exit 1;;
        htm|html|xhtml) w3m -dump "${FILE_PATH}";;
	iso) iso-info -f --no-header "${FILE_PATH}"|bat ;;
	json) bat "${FILE_PATH}" ;;
	o|exe|appimage) handle_fallback;;
    esac
}

handle_mime() {
    local mimetype="${1}"
    case "${mimetype}" in
	text/plain) bat "${FILE_PATH}" exit 1;;
	text/troff) man ./ "${FILE_PATH}" | col -b ;;
        text/* | */xml)
            if [ "$( stat --printf='%s' -- "${FILE_PATH}" )" -gt "${HIGHLIGHT_SIZE_MAX}" ]; then
                exit 2
            fi
            if [ "$( tput colors )" -ge 256 ]; then
                local pygmentize_format='terminal256'
                local highlight_format='xterm256'
            else
                local pygmentize_format='terminal'
                local highlight_format='ansi'
            fi
            highlight --replace-tabs="${HIGHLIGHT_TABWIDTH}" --out-format="${highlight_format}" \
                --style="${HIGHLIGHT_STYLE}" --force -- "${FILE_PATH}"
            exit 2;;
        application/javascript) bat "${FILE_PATH}" exit 1;;
        image/*) chafa --fill=block --symbols=block -c 256 -s 55x"${HEIGHT}" "${FILE_PATH}" || exit 1;;
        video/* | audio/*|application/octet-stream)
            mediainfo "${FILE_PATH}"
            exiftool "${FILE_PATH}"
            exit 1;;
    esac
}

handle_fallback() {
    echo '----- File Type Classification -----' && file --dereference --brief -- "${FILE_PATH}"
    exit 1
}


MIMETYPE="$( file --dereference --brief --mime-type -- "${FILE_PATH}" )"
handle_extension
handle_mime "${MIMETYPE}"

exit 1
